# Generated by Django 4.1.3 on 2022-12-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfamilia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hija',
            name='profesion',
        ),
    ]
